### ISSUE TITLE
The template "report-bib" needs update

### ISSUE THREAD

**Issue by juniuspan** [lauritzsh/pandoc-markdown-template#7]
Hi Lauritzsh,

Thanks for sharing you template. 
I found the "template.tex" in "report-bib" should be updated due to the upgrade of the Pandoc, I got this error information when I ran the codes:
> ! LaTeX Error: Environment cslreferences undefined.

just adding the below codes could solve the problem:
`
$if(csl-refs)$
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newenvironment{cslreferences}%
  {$if(csl-hanging-indent)$\setlength{\parindent}{0pt}%
  \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces$endif$}%
  {\par}
$endif$
`

FYI!

Jun

**Comment by lauritzsh** [comment]
Hi, thanks for sharing your fix. It's a long time since I've used the project and I don't have LaTeX installed on my machine to verify, could you instead make a pull request and I will merge it in?

**Comment by juniuspan** [comment]
@lauritzsh I've made the pull request. It's my first time to initiate a pull request, I'm not sure whether I did it right.

**Comment by lauritzsh** [comment]
Looks good, I have merged #8 in. Thanks for contributing 👍
