### ISSUE TITLE
How do I set font of headings equal to font of text?

### ISSUE THREAD

**Issue by quinn-dougherty** [lauritzsh/pandoc-markdown-template#9]
I'm not sure what setting is making the font of headings sans serif and the font of text the normal Latex serif, but how do I unify them to be the latex serif?

**Comment by lauritzsh** [comment]
Hello, I did a little digging about the mix of serif and sans serif, and it comes from using the KOMA-Script for document class, where they seem to have made a conscious choice about this. See [this](https://tex.stackexchange.com/a/289862/23507) for more.

To actually fix it (solution from the same link), just add `headings=standardclasses` to `documentclass` as an option. In context, you'd have `\documentclass[12pt,a4paper,headings=standardclasses]{scrartcl}`. The result should look like this:

![image](https://user-images.githubusercontent.com/1979410/142725275-859336d2-4ab3-47a8-9273-f957a34d59a8.png)

**Comment by quinn-dougherty** [comment]
fantastic, it worked for me, thanks!
